apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-controller-deployment
  labels:
    app: configmap-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-controller
  template:
    metadata:
      labels:
        app: configmap-controller
    spec:
      serviceAccountName: configmap-controller
      containers:
      - name: configmap-controller
        image: caladreas/configmap-controller
        imagePullPolicy: Always
